### ISSUE TITLE
ArduinoLowPowerClass::wakeOn* methods attempt to access private variables

### ISSUE THREAD

**Issue by glenmurphy** [ElectronicCats/ArduinoLowPower#2]
The wakeOn* methods just added to samd/ArduinoLowPower.cpp attempt to access private variables in other classes, causing compilation errors.

For example,
   ArduinoLowPowerClass::wakeOnWire accesses wire->sercom

'sercom' is defined as private in:
https://github.com/ElectronicCats/ArduinoCore-samd/blob/master/libraries/Wire/Wire.h

**Comment by sabas1080** [comment]
Hi @glenmurphy 

For use this fork of Arduino LowPower you must used this pullrequest in our Arduino Core 
https://github.com/ElectronicCats/ArduinoCore-samd/pull/2
