### ISSUE TITLE
BastWAN not waking up from sleep

### ISSUE THREAD

**Issue by GitMF85** [ElectronicCats/ArduinoLowPower#3]
Hello,

I was able to compile the example code for this library for the BastWAN board, but it didn´t get out of sleep.  Analyzing the ArduinoLowPower.cpp file,  I noticed that the code did lockup  at line 60 "GCLK->GENCTRL[0].reg = gclkConfig.reg;". Any idea what the problem can be? Thanks

`/*
  TimedWakeup

  This sketch demonstrates the usage of Internal Interrupts to wakeup a chip in sleep mode.
  Sleep modes allow a significant drop in the power usage of a board while it does nothing waiting for an event to happen. Battery powered application can take advantage of these modes to enhance battery life significantly.

  In this sketch, the internal RTC will wake up the processor every 2 seconds.
  Please note that, if the processor is sleeping, a new sketch can't be uploaded. To overcome this, manually reset the board (usually with a single or double tap to the RESET button)

  This example code is in the public domain.
*/
#include <Arduino.h>
#include "ArduinoLowPower.h"

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  // Uncomment this function if you wish to attach function dummy when RTC wakes up the chip
  // LowPower.attachInterruptWakeup(RTC_ALARM_WAKEUP, dummy, CHANGE);

}

void loop() {
  digitalWrite(LED_BUILTIN, HIGH);
  delay(500);
  digitalWrite(LED_BUILTIN, LOW);
  delay(500);
  // Triggers a 2000 ms sleep (the device will be woken up only by the registered wakeup sources and by internal RTC)
  // The power consumption of the chip will drop consistently
  LowPower.sleep(2000);
}

void dummy() {
  // This function will be called once on device wakeup
  // You can do some little operations here (like changing variables which will be used in the loop)
  // Remember to avoid calling delay() and long running functions since this functions executes in interrupt context
}`

**Comment by sabas1080** [comment]
Did you try uncommenting and using a function?

LowPower.attachInterruptWakeup(RTC_ALARM_WAKEUP, dummy, CHANGE);

**Comment by GitMF85** [comment]
Yes, I did uncomment that line, but without any change.

**Comment by GitMF85** [comment]
I have been looking at the ArduinoLowPower.cpp file and added some Serial.print lines. I noticed that the code stops before "Serial.println("d1.1");".
It looks like changing the clock source from "GCLK_GENCTRL_SRC_DFLL48M_Val" to "GCLK_GENCTRL_SRC_OSCULP32K_Val" is stopping the code.



	gclkConfig.reg = 0;
        Serial.println("d1.0");
	gclkConfig.reg = GCLK->GENCTRL[0].reg;
	Serial.println(gclkConfig.bit.SRC);
	gclkConfig.bit.SRC = GCLK_GENCTRL_SRC_OSCULP32K_Val;// GCLK_GENCTRL_SRC_OSCULP32K_Val ;//GCLK_GENCTRL_SRC_OSC16M_Val
	GCLK->GENCTRL[0].reg = gclkConfig.reg;
        Serial.println("d1.1");
	while (GCLK->SYNCBUSY.reg & GCLK_SYNCBUSY_GENCTRL(0)) {

**Comment by sabas1080** [comment]
Try with Clock source 32Khz

<img width="773" alt="Captura de Pantalla 2021-04-12 a la(s) 10 08 26" src="https://user-images.githubusercontent.com/2874292/114417236-090a1000-9b77-11eb-9af2-149bc0f62001.png">

**Comment by GitMF85** [comment]
That fixed it, thanks
