### ISSUE TITLE
Clock slowdown after the first call to LowPower.sleep()

### ISSUE THREAD

**Issue by REGIOIGER** [ElectronicCats/ArduinoLowPower#4]
Hi, in testing the TimedWakeup example from the ArduinoLowPower library the only way it partially worked for me with the BastWAN is using the 32Khz oscillator. I used a delay(500) to blink the built in LED, but on the second cycle (and subsequent cycles) of the loop() the delay slows down, as if the clock were lowering the frequency. In tests I have been doing this affects my serial communication for example.

Llink to a video of the behavior: 
https://youtu.be/osNfKCASaw8

![Captura de pantalla de 2021-06-24 21-26-35](https://user-images.githubusercontent.com/5591656/123424661-c3aa8b80-d586-11eb-8fcd-4137c3727548.png)

**Comment by sabas1080** [comment]
Hi @REGIOIGER 

can you share your sketch or code?

**Comment by REGIOIGER** [comment]
Thanks for a quick response @sabas1080 
The code is the same that TimedWakeup example in the library
/*
  TimedWakeup

  This sketch demonstrates the usage of Internal Interrupts to wakeup a chip in sleep mode.
  Sleep modes allow a significant drop in the power usage of a board while it does nothing waiting for an event to happen. Battery powered application can take advantage of these modes to enhance battery life significantly.

  In this sketch, the internal RTC will wake up the processor every 2 seconds.
  Please note that, if the processor is sleeping, a new sketch can't be uploaded. To overcome this, manually reset the board (usually with a single or double tap to the RESET button)

  This example code is in the public domain.
*/

#include "ArduinoLowPower.h"

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  // Uncomment this function if you wish to attach function dummy when RTC wakes up the chip
  // LowPower.attachInterruptWakeup(RTC_ALARM_WAKEUP, dummy, CHANGE);
}

void loop() {
  digitalWrite(LED_BUILTIN, HIGH);
  delay(500);
  digitalWrite(LED_BUILTIN, LOW);
  delay(500);
  // Triggers a 2000 ms sleep (the device will be woken up only by the registered wakeup sources and by internal RTC)
  // The power consumption of the chip will drop consistently
  LowPower.sleep(2000);
}

void dummy() {
  // This function will be called once on device wakeup
  // You can do some little operations here (like changing variables which will be used in the loop)
  // Remember to avoid calling delay() and long running functions since this functions executes in interrupt context
}

**Comment by sabas1080** [comment]
I'm testing and it seems to work fine. You mention serial communication but I don't see it in the example, serial communication is complicated in interruptions

**Comment by REGIOIGER** [comment]
I try with two BastWAN and get the same behavior like in the video https://youtu.be/osNfKCASaw8 
also tested on windows and the same thing, the delay(500) lasts more than 500 ms after the first loop cycle
Sometimes with the INTERNAL OSCILLATOR selected it seems to work the first time, but when disconnecting and connecting the board it freezes. Sorry for do mention of serial communication, I was using a code that uses serial communication with a GPS that was not working and I suspected that maybe something was wrong with the clock configuration, so I decided to first try TimeWakeup which is a bit simpler.

**Comment by sabas1080** [comment]
Are you considering sleep time? that's why there is an "extra delay"=sleep time(2000ms), you can validate with this example

```
#include "ArduinoLowPower.h"

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  // Uncomment this function if you wish to attach function dummy when RTC wakes up the chip
  // LowPower.attachInterruptWakeup(RTC_ALARM_WAKEUP, dummy, CHANGE);
}

void loop() {
  for(int i=0;i<10;i++){
    digitalWrite(LED_BUILTIN, HIGH);
    delay(500);
    digitalWrite(LED_BUILTIN, LOW);
    delay(500);
  }
  // Triggers a 2000 ms sleep (the device will be woken up only by the registered wakeup sources and by internal RTC)
  // The power consumption of the chip will drop consistently
  LowPower.sleep(2000);
}

void dummy() {
  // This function will be called once on device wakeup
  // You can do some little operations here (like changing variables which will be used in the loop)
  // Remember to avoid calling delay() and long running functions since this functions executes in interrupt context
}
```

**Comment by REGIOIGER** [comment]
I test the example provided, this is the result https://youtu.be/deOQz89VN9g

**Comment by sabas1080** [comment]
@REGIOIGER ok, it seems to be a problem with the setting of the clocks when waking up, I have tagged it as a bug
